sudo: required
services:
  - docker

before_install:
  - docker build -t geosony/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true geosony/client-test npm run test

after_success:
  - docker build -t geosony/multi-client ./client
  - docker build -t geosony/multi-nginx ./nginx
  - docker build -t geosony/multi-server ./server
  - docker build -t geosony/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push into docker hub
  - docker push geosony/multi-client
  - docker push geosony/multi-nginx
  - docker push geosony/multi-server
  - docker push geosony/multi-worker

  deploy:
    provider: elastickbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-304191806274
    bucket_path: docker-multi
    on:
      branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY





